"""empty message

Revision ID: f12c4e7cca44
Revises: None
Create Date: 2016-06-01 12:00:20.478068

"""

# revision identifiers, used by Alembic.
revision = 'f12c4e7cca44'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id')
    )
    op.create_index(op.f('ix_bucketlists_date_created'), 'bucketlists', ['date_created'], unique=False)
    op.create_table('bucketlistitems',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=256), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('bucketlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_id'], ['bucketlists.id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_index(op.f('ix_bucketlistitems_date_created'), 'bucketlistitems', ['date_created'], unique=False)
    op.create_index(op.f('ix_bucketlistitems_done'), 'bucketlistitems', ['done'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bucketlistitems_done'), table_name='bucketlistitems')
    op.drop_index(op.f('ix_bucketlistitems_date_created'), table_name='bucketlistitems')
    op.drop_table('bucketlistitems')
    op.drop_index(op.f('ix_bucketlists_date_created'), table_name='bucketlists')
    op.drop_table('bucketlists')
    op.drop_table('users')
    ### end Alembic commands ###
